version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    networks:
      - demo-net
    depends_on:
      - pg-db
  pg-db:
    image: postgres:10.7
    environment:
        POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    networks:
      - demo-net
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
networks:
  demo-net: